"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import {
  CheckCircle2,
  FileText,
  FileJson2,
  FileLock2,
  Download,
  Lock,
  Circle,
} from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/primitives/StatusBadge";
import { useCases } from "@/context/CaseContext";

export function ExportClient({ caseId }: { caseId: string }) {
  const { getCase, markExported, setActiveCaseId } = useCases();
  const kase = getCase(caseId);
  const [exported, setExported] = useState<string[]>([]);

  useEffect(() => setActiveCaseId(caseId), [caseId, setActiveCaseId]);

  if (!kase) {
    return (
      <div className="p-10 text-sm text-muted-foreground">
        Case not found. <Link className="text-status-ok underline" href="/">Back to dashboard</Link>
      </div>
    );
  }

  const approved = kase.reviewDecision?.outcome === "approved-for-tps-recalculation";
  const events = [...kase.auditTrail].reverse();

  function doExport(kind: string) {
    markExported(caseId, kind);
    setExported((e) => [...e, kind]);
    toast.success(`${kind} prepared`, {
      description: "Mock export — in production this package is generated by the backend.",
    });
  }

  const OPTIONS = [
    {
      id: "Research report PDF",
      icon: FileText,
      desc: "Case summary, constraint verdicts with rationale, DVH snapshots and audit digest for human review.",
      enabled: true,
      needsApproval: true,
    },
    {
      id: "Structured JSON summary",
      icon: FileJson2,
      desc: "Machine-readable case, prescription, structure set, candidate metrics and decision record (no imaging).",
      enabled: true,
      needsApproval: true,
    },
    {
      id: "DICOM-RT export package",
      icon: FileLock2,
      desc: "RTDOSE/RTPLAN hand-off bundle. Disabled — available after validated backend integration (stage 6).",
      enabled: false,
      needsApproval: false,
    },
  ];

  return (
    <div className="min-h-full">
      <div className="mx-auto max-w-5xl px-6 py-8">
        <header className="flex flex-wrap items-end justify-between gap-4">
          <div>
            <p className="text-label text-muted-foreground">Export &amp; audit</p>
            <h1 className="num mt-1 flex items-center gap-3 text-xl font-semibold tracking-tight">
              {kase.id} <StatusBadge status={kase.status} />
            </h1>
          </div>
        </header>

        {!approved && (
          <div className="mt-6 rounded-md border border-warn/30 bg-warn-soft px-4 py-3 text-sm text-status-warn" role="note">
            No approval-for-recalculation decision on file yet. Exports are permitted for research
            purposes, but the TPS hand-off checklist stays incomplete until the plan review is signed.
          </div>
        )}

        {/* export options */}
        <section aria-label="Export options" className="mt-7 grid grid-cols-1 gap-4 md:grid-cols-3">
          {OPTIONS.map((o, i) => {
            const Icon = o.icon;
            const done = exported.includes(o.id);
            return (
              <motion.div
                key={o.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.06, duration: 0.28 }}
                className={
                  "panel-edge relative flex flex-col rounded-md border p-4 " +
                  (o.enabled ? "border-border bg-card" : "border-border bg-card/50 opacity-70")
                }
              >
                <Icon className={o.enabled ? "h-5 w-5 text-status-ok" : "h-5 w-5 text-muted-foreground"} aria-hidden />
                <h2 className="mt-3 text-sm font-medium">{o.id}</h2>
                <p className="mt-1.5 flex-1 text-xs leading-relaxed text-muted-foreground">{o.desc}</p>
                <div className="mt-4">
                  {o.enabled ? (
                    <Button
                      size="sm"
                      variant="secondary"
                      disabled={done}
                      onClick={() => doExport(o.id)}
                    >
                      {done ? (
                        <>
                          <CheckCircle2 className="h-3.5 w-3.5 text-status-ok" aria-hidden /> Prepared
                        </>
                      ) : (
                        <>
                          <Download className="h-3.5 w-3.5" aria-hidden /> Prepare mock file
                        </>
                      )}
                    </Button>
                  ) : (
                    <Button size="sm" variant="secondary" disabled title="Requires validated backend integration">
                      <Lock className="h-3.5 w-3.5" aria-hidden /> Unavailable in prototype
                    </Button>
                  )}
                </div>
              </motion.div>
            );
          })}
        </section>

        {/* audit timeline */}
        <section aria-label="Audit timeline" className="mt-9">
          <h2 className="text-label mb-3 text-muted-foreground">Audit timeline</h2>
          <ol className="relative space-y-0 overflow-hidden rounded-md border border-border bg-card">
            {events.map((e, i) => (
              <li key={e.id} className="relative flex gap-4 px-5 py-3.5">
                {i < events.length - 1 && (
                  <span aria-hidden className="absolute left-[34px] top-12 h-full w-px bg-border" />
                )}
                <span
                  aria-hidden
                  className={
                    "z-10 mt-1 flex h-[18px] w-[18px] shrink-0 items-center justify-center rounded-full border " +
                    (e.severity === "success"
                      ? "border-ok/40 bg-ok-soft"
                      : e.severity === "warning"
                        ? "border-warn/40 bg-warn-soft"
                        : "border-border bg-secondary")
                  }
                >
                  {e.severity === "success" ? (
                    <CheckCircle2 className="h-3 w-3 text-status-ok" />
                  ) : (
                    <Circle className="h-2 w-2 text-muted-foreground" />
                  )}
                </span>
                <div className="min-w-0 flex-1">
                  <p className="text-[13px] leading-snug">{e.action}</p>
                  <p className="num mt-1 text-[11px] text-muted-foreground">
                    {e.actor} · {new Date(e.timestamp).toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" })}
                  </p>
                </div>
              </li>
            ))}
          </ol>
          <p className="mt-3 text-[11px] leading-relaxed text-muted-foreground">
            Every consequential action is recorded here. In production these entries are immutable
            server-side records backing the RBAC and audit requirements.
          </p>
        </section>

        {/* safety footer */}
        <footer className="mt-8 flex items-start gap-2.5 rounded-md border border-border bg-secondary p-4">
          <Lock className="mt-0.5 h-3.5 w-3.5 shrink-0 text-muted-foreground" aria-hidden />
          <p className="text-xs leading-relaxed text-muted-foreground">
            Meridian exports research material only. Nothing exported from this system may be used
            for treatment delivery without full local TPS recalculation, patient-specific QA and
            clinician approval under your institution&apos;s clinical governance.
          </p>
        </footer>
      </div>
    </div>
  );
}
